FROM mongo:latest
# Copia os 3 ficheiros JSON e o script de importação
COPY filmes.json  /docker-entrypoint-initdb.d/
COPY atores.json  /docker-entrypoint-initdb.d/
COPY generos.json /docker-entrypoint-initdb.d/
COPY mongo-init/import.sh /docker-entrypoint-initdb.d/