services:

  mongodb:
    build:
      context: ./api_dados
      dockerfile: Dockerfile.mongo
    container_name: cinema_mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - cinema-network

  api_dados:
    build:
      context: ./api_dados
      dockerfile: Dockerfile
    container_name: cinema_api
    environment:
      - MONGO_URL=mongodb://mongodb:27017/cinema
    depends_on:
      - mongodb
    networks:
      - cinema-network

  interface:
    build:
      context: ./interface
      dockerfile: Dockerfile.interface
    container_name: cinema_interface
    ports:
      - "7780:7780"
    environment:
      - API_URL=http://cinema_api:7779
    depends_on:
      - api_dados
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge

volumes:
  mongo_data:
